version: "3"

services:
  apache:
    build: # инструкции для создания образа
      # контекст (путь к каталогу, содержащему Dockerfile)
      context: ./bin/php8
    container_name: apache
    restart: "always"
    ports:
      - "81:80"
    # Cвязываем контейнеры вместе
    links:
      - database
    volumes:
      #  Монтируем директорию с php-скриптом внутрь контейнера
      - ./www:/var/www/html
      #  Монтируем файл конфигурации php.ini внутрь контейнера
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      #  Монтируем файл конфигурации Apache2 внутрь контейнерa
      - ./config/vhosts/apache2.conf:/etc/apache2/apache2.conf
      - ./config/vhosts/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      # Монтируем файл конфигурации портов
      - ./config/vhosts/ports.conf:/etc/apache2/ports.conf

  database:
    build:
      context: "./bin/mysql8"
    container_name: mysql8
    restart: "always"
    ports:
      - "3306:3306"
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    volumes:
      - ./config/initdb:/docker-entrypoint-initdb.d
      - ./data/mysql:/var/lib/mysql
      - ./config/mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: tiger


  phpmyadmin:
    image: phpmyadmin
    container_name: PMA
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_PASSWORD: tiger
      MYSQL_ROOT_PASSWORD: tiger
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    ports:
      - "8080:80"
    volumes:
      - ./config/pma/apache2.conf:/etc/apache2/apache2.conf

  nginx:
    build:
      context: "./bin/nginx/"
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
      - ./www:/var/www/html
    depends_on:
      - apache







